[package]
name = "mehsh"
version = "0.0.1"
edition = "2024"
description = "a meh mesh processing library in Rust"
license = "MIT"
repository = "https://github.com/maximsnoep/mehsh"
keywords = ["mesh", "geometry", "processing", "rust"]
categories = ["graphics", "data-structures"]

[features]
default = []
obj = ["dep:obj"]
stl = ["dep:stl_io"]
all = [ "obj", "stl"]

[dependencies]
itertools = "0.15.0"
tracing = "0.1.44"
nalgebra = "0.33.2"
thiserror = "2.0.17"
slotmap = { version = "1.0.7", features = ["serde"] }
bimap = { version = "0.6.3", features = ["serde"] } # for face and vertex ID maps
kdtree = "0.7.0" # for vertex lookup
geometry-predicates = "0.3.0" # Shewchuk's adaptive precision geometry predicates
bvh = "0.11.0" # for face lookup
orx-parallel = "3.4.0"

# Optional features
obj = { version = "0.10.2", optional = true }
stl_io = { version = "0.8.5", optional = true }
serde = { version = "1.0.188" }

[lints]
workspace = true