[package]
name = "gui"
version = "0.1.0"
edition = "2024"

[features]
snoep6 = []
bettina = []
gray = []
pastel = []
light_mode = []
quad = ["dep:dualcube-quad"]
hex = ["dep:dualcube-hex"]

[dependencies]
dualcube = { path = "../../crates/dualcube" }
dualcube-hex = { path = "../../crates/dualcube-hex", optional = true }
dualcube-quad = { path = "../../crates/dualcube-quad", optional = true }
io = { path = "../../crates/dualcube-io" }
mehsh = { path = "../../crates/mehsh" }
mehsh-bevy = { path = "../../crates/mehsh-bevy" }

bevy = { version = "0.18.0", default-features = false, features = [
	"dynamic_linking",

	# Core
    "std",
    "multi_threaded",

    # App/window/input basics
    "bevy_log",
    "bevy_window",
    "bevy_winit",
    "bevy_input_focus",
    "keyboard",
    "mouse",

    # Assets/rendering
    "bevy_asset",
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_camera",
    "bevy_image",
    "bevy_mesh",
    "bevy_light",
    "bevy_pbr",
    "bevy_shader",

    # Your app uses Gizmos and MeshRayCast
    "bevy_gizmos",
    "bevy_gizmos_render",
    "bevy_picking",
    "mesh_picking",

    # Needed by Bevy UI / bevy_egui interaction
    "bevy_ui",
    "bevy_ui_render",

    # Diagnostics
    "sysinfo_plugin",

    # Windows desktop backend
    "raw_vulkan_init",
] }

# Egui UI
bevy_egui = "0.39.1"
egui_dock = "0.18.0"
# File dialogs
rfd = { version = "0.17.2", default-features = false }

# Bevy plugins
bevy-orbit-camera = "0.3.3"
# bevy-orbit-camera = { path = "../../../bevy-orbit-camera" }
bevy-axes-gizmo = "0.3.1"
# bevy-axes-gizmo = { path = "../../../bevy-axes-gizmo" }
bevy-blossom = "0.2.0"
# bevy-blossom = { path = "../../../bevy-blossom" }
bevy-toon = "0.2.0"
# bevy-toon = { path = "../../../bevy-toon" }
bevy-wicon = "0.18.1"
# bevy-wicon = { path = "../../../bevy-wicon" }

[lints]
workspace = true
