[package]
name = "dualcube"
version = "0.1.0"
edition = "2024"

[dependencies]
mehsh = { path = "../../utils/mehsh", features = ["tetgen"] }
grapff = { path = "../../utils/grapff" }
log = "0.4.27"
itertools = "0.15.0"
slotmap = "1.0.7"
ordered-float = "5.0.0"
bimap = "0.6.3"
rand = "0.10.1"
faer = "0.24.0"
faer_gmres = "0.5.0"
serde = { version = "1.0.188", features = ["rc"] }
thiserror = "2.0.17"
orx-parallel = "3.4.0"
num-complex = "0.4"

[lints]
workspace = true